[package]
name = "rust_some"
version = "0.1.0"
authors = ["nikky"]
edition = "2018"
include = ["src/**/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
